toc:
  - name: Arrays
    children:
      - toArr
      - flatten

  - name: Checks
    children:
      - is
      - isPlainObj
      - isEmpty
      - isNil
      - isNum
      - isStr
      - isBool
      - isFn
      - isArr

  - name: Objects
    children:
      - toObj
      - mapObj
      - filterObj
