toc:
  - name: Objects
    children:
      - path
      - mapObj
      - filterObj
      - reduceObj
      - toObj
      - flattenObj
      - fallbackTo

  - name: Arrays
    children:
      - toArr
      - flattenArr

  - name: Functions
    children:
      - always
      - T
      - F
      - noop
      - identity
      - compose
      - pipe
      - curry
      - curryN
      - once
      - debounce
      - throttle

  - name: Checks
    children:
      - is
      - isEmpty
      - isEmptyObj
      - isPlainObj
      - isNil
      - isNum
      - isStr
      - isBool
      - isFn
      - isArr
