toc:
  - name: Objects
    children:
      - path
      - mapObj
      - filterObj
      - reduceObj
      - flattenObj
      - fallbackTo

  - name: Arrays
    children:
      - toArr
      - flattenArr
      - initArr

  - name: Functions
    children:
      - always
      - noop
      - identity
      - flip
      - compose
      - pipe
      - curry
      - curryN
      - once
      - debounce
      - throttle
      - memoize

  - name: Promises
    children:
      - wait
      - reflect
      - alwaysResolve
      - queue
      - concurrentN
      - timeout
      - promisify
      - deferredPromise
      - debouncePromise
      - toPromise

  - name: Checks
    children:
      - is
      - isEmpty
      - isEmptyObj
      - isPlainObj
      - isNil
      - isNum
      - isStr
      - isBool
      - isFn
      - isThenable
      - isArr
      - isObj
