toc:
  - name: Arrays
    children:
      - toArr
      - flatten

  - name: Objects
    children:
      - toObj
      - mapObj
      - filterObj
      - path

  - name: Functions
    children:
      - always
      - T
      - F
      - noop
      - identity
      - compose
      - pipe
      - curry
      - curryN
      - once
      - debounce
      - throttle

  - name: Logic
    children:
      - is
      - isPlainObj
      - isEmpty
      - isNil
      - isNum
      - isStr
      - isBool
      - isFn
      - isArr
      - fallbackTo
